name: myapp
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.1


  provider: ^6.0.5
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.7
  intl: ^0.18.0
  audioplayers: ^5.0.0


dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/mp3/
  fonts: 
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterExtraBold.ttf
          weight: 800
    - family: Noto Sans
      fonts: 
        - asset: assets/fonts/NotoSansRegular.ttf
          weight: 400

    - family: Megrim
      fonts:
        - asset: assets/fonts/Megrim.ttf
